#! /bin/sh

xsetroot -cursor_name left_ptr

bspc config border_width        5
bspc config window_gap         14
bspc config top_padding	       17

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true

focused_border_color	#529ABF
normal_border_color	#1782B7
active_border_color	#1782B7

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a thunar desktop=^4 floating=on
bspc rule -a Firefox desktop=^2
bspc rule -a deluge desktop=^7
bspc rule -a VirtualBox desktop=^5
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv floating=on
bspc rule -a qbittorrent desktop=^7

panel &
compton -c --backend glx --vsync opengl-swc &
nitrogen --restore &
